<div class="box_preview">
    <h5><?php echo $this->event->title; ?></h5>
    <div class="box_preview_item">
        <label>Descripci&oacute;n del Evento:</label>
        <p>
            <?php echo $this->event->description; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Empresa:</label>
        <p>
            <?php echo $this->event->company; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Contacto:</label>
        <p>
            <?php echo $this->event->contact; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Telefono(s):</label>
        <p>
            <?php echo $this->event->phone; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>E-mail:</label>
        <p>
            <?php echo $this->event->email; ?>
        </p>
    </div>
</div>
