<div class="box_preview">
    <h5><?php echo $this->offer->title; ?></h5>
    <div class="box_preview_item">
        <label>Descripci&oacute;n del Puesto:</label>
        <p>
            <?php echo $this->offer->description; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Empresa:</label>
        <p>
            <?php echo $this->offer->company; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Contacto:</label>
        <p>
            <?php echo $this->offer->contact; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>Telefono(s):</label>
        <p>
            <?php echo $this->offer->phone; ?>
        </p>
    </div>
    <div class="box_preview_item">
        <label>E-mail:</label>
        <p>
            <?php echo $this->offer->email; ?>
        </p>
    </div>
</div>
