<?php if ('development' == APPLICATION_ENV): ?>
    <h1>An error occurred</h1>
    <h2><?php echo $this->message ?></h2>

    <h3>Exception information:</h3>
    <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo var_export($this->request->getParams(), true) ?></pre>
<?php else: ?>
    <div class="error404">
        <p class="sorry">La p&aacute;gina que intentas solicitar no est&aacute; disponible en el servidor. </p>
        <img src="<?php echo BASE_URL; ?>css/default/images/404_bg.jpg"/>
    </div>
<?php endif; ?>
