<table width="100%" class="datatable" id="tablePublicacion">
    <thead>
        <tr>
            <th width="5%">Item</th>
            <th width="60%">Titulo</th>
            <th width="5%">Fecha</th>
            <th width="5%">Inicia</th>
            <th width="5%">Termina</th>
            <th width="15%">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->publicacionesList as $publicacion): ?>
        <tr id="<?php echo $publicacion->id; ?>">
            <td class="item"><?php echo $publicacion->id; ?></td>
            <td><?php echo $publicacion->title; ?></td>
            <td><?php echo $publicacion->eventDate; ?></td>
            <td><?php echo $publicacion->startTime; ?></td>
            <td><?php echo $publicacion->endTime; ?></td>
            <td align="center">
                <a href="<?php echo BASE_URL; ?>evento/borrar/id/<?php echo $publicacion->id ?>" class="action borrar">Borrar</a>|
                <a href="<?php echo BASE_URL; ?>evento/editar/id/<?php echo $publicacion->id ?>" class="editar">Editar</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
<script type="text/javascript">
$(document).ready(function(){
    var fixContainer = $('#fixContainer');
    $('#tablePublicacion').delegate('a.action', 'click', function(e){
        e.preventDefault();
        var current = $(this);
        var currentRow = current.parents('tr');
        var currentId  = currentRow.attr('id');
        
        if( current.hasClass('borrar') ){
            if( confirm('Seguro de borrar este evento?') ){
                fixContainer.block();
                $.post(current.attr('href'), {id : currentId}, function(response){
                    if(response && response.status){
                        currentRow.fadeOut().remove();    
                    }
                    fixContainer.unblock();
                }, 'json');
            }
        }
    });
});
</script>
